import pymongo
from dotenv import load_dotenv
from datetime import datetime
import os
import time

dotenv_path = '/Users/hojuicheng/Desktop/personal_project/Appworks_Personal/.env'
load_dotenv(dotenv_path)


# Mongo atlas
CONNECTION_STRING = os.getenv("MONGO_ATLAS_USER")
client = pymongo.MongoClient(CONNECTION_STRING)

# Select a database and collection
db = client["personal_project"]
user_collection = db["user"]
house_collection = db["house"]


def get_next_house_id():
    # Find and update the user_id counter
    counter_doc = client['personal_project']['house'].counters.find_one_and_update(
        {"_id": "house_id"},
        {"$inc": {"seq": 1}},
        upsert=True,  # Create the counter if it doesn't exist
        return_document=True
    )
    return counter_doc["seq"]


house_data = [
    {
        "fake_id": 1,
        "title": "信義區高級住宅",
        "price": 100000,
        "address": "台北市信義區松壽路",
        "type": "電梯大樓",
        "usage": None,
        "age": 10,
        "face": None,
        "env": "無",
        "size": 100,
        "short_stay": "12個月",
        "cook": True,
        "move_date": "2024年04月10日",
        "pet": "不可",
        "fee_contain": True,
        "gender": "男女皆可",
        "deposit": -1,
        "identy": "不限",
        "stay_landlord": True,
        "park": True,
        "equip": ["熱水器", "天然瓦斯", "洗衣機", "瓦斯爐", "冰箱", "冷氣"],
        "furniture": ["衣櫃"],
        "floor": "3 / 4 樓",
        "corner": True,
        "center": False,
        "top_add": False,
        "img_url": "https://pic.hfcdn.com/res/DrawImage/ShowPic/400/300/HFRENT05/1831862/1?t=0921",
        "layout": "3房(室)2廳1衛"
    },
    {
        "fake_id": 2,
        "url": "https://fake_url.com",
        "title": "松山區四房高級住宅",
        "price": 200000,
        "address": "台北市松山區敦化路",
        "type": "電梯大樓",
        "usage": None,
        "age": 10,
        "face": None,
        "env": "無",
        "size": 100,
        "short_stay": "12個月",
        "cook": True,
        "move_date": "2024年04月10日",
        "pet": "不可",
        "fee_contain": True,
        "gender": "男女皆可",
        "deposit": -1,
        "identy": "不限",
        "stay_landlord": True,
        "park": True,
        "equip": ["熱水器", "天然瓦斯", "洗衣機", "瓦斯爐", "冰箱", "冷氣"],
        "furniture": ["衣櫃"],
        "floor": "3 / 4 樓",
        "corner": True,
        "center": False,
        "top_add": False,
        "img_url": "https://pic.hfcdn.com/res/DrawImage/ShowPic/400/300/HFRENT05/1831862/1?t=0921",
        "layout": "4房(室)2廳1衛"
    },
    {
        "fake_id": 3,
        "url": "https://fake_url.com",
        "title": "信義區五房高級住宅",
        "price": 200000,
        "address": "台北市信義區松仁路",
        "type": "電梯大樓",
        "usage": None,
        "age": 10,
        "face": None,
        "env": "無",
        "size": 100,
        "short_stay": "12個月",
        "cook": True,
        "move_date": "2024年04月10日",
        "pet": "不可",
        "fee_contain": True,
        "gender": "男女皆可",
        "deposit": -1,
        "identy": "不限",
        "stay_landlord": True,
        "park": True,
        "equip": ["熱水器", "天然瓦斯", "洗衣機", "瓦斯爐", "冰箱", "冷氣"],
        "furniture": ["衣櫃"],
        "floor": "3 / 4 樓",
        "corner": True,
        "center": False,
        "top_add": False,
        "img_url": "https://pic.hfcdn.com/res/DrawImage/ShowPic/400/300/HFRENT05/1831862/1?t=0921",
        "layout": "4房(室)2廳1衛"
    },
    {
        "fake_id": 9,
        "url": "https://fake_url.com",
        "title": "信義區四房高級住宅",
        "price": 200000,
        "address": "台北市信義區松壽路",
        "type": "電梯大樓",
        "usage": None,
        "age": 10,
        "face": None,
        "env": "無",
        "size": 100,
        "short_stay": "12個月",
        "cook": True,
        "move_date": "2024年04月10日",
        "pet": "不可",
        "fee_contain": True,
        "gender": "男女皆可",
        "deposit": -1,
        "identy": "不限",
        "stay_landlord": True,
        "park": True,
        "equip": ["熱水器", "天然瓦斯", "洗衣機", "瓦斯爐", "冰箱", "冷氣"],
        "furniture": ["衣櫃"],
        "floor": "3 / 4 樓",
        "corner": True,
        "center": False,
        "top_add": False,
        "img_url": "https://pic.hfcdn.com/res/DrawImage/ShowPic/400/300/HFRENT05/1831862/1?t=0921",
        "layout": "4房(室)2廳1衛"
    },
    {
        "fake_id": 4,
        "title": "信義區陶朱隱園高級住宅",
        "price": 300000,
        "address": "台北市信義區光復路",
        "type": "電梯大樓",
        "usage": None,
        "age": 10,
        "face": None,
        "env": "無",
        "size": 100,
        "short_stay": "12個月",
        "cook": True,
        "move_date": "2024年04月10日",
        "pet": "不可",
        "fee_contain": True,
        "gender": "男女皆可",
        "deposit": -1,
        "identy": "不限",
        "stay_landlord": True,
        "park": True,
        "equip": ["熱水器", "天然瓦斯", "洗衣機", "瓦斯爐", "冰箱", "冷氣"],
        "furniture": ["衣櫃"],
        "floor": "3 / 4 樓",
        "corner": True,
        "center": False,
        "top_add": False,
        "img_url": "https://pic.hfcdn.com/res/DrawImage/ShowPic/400/300/HFRENT05/1831862/1?t=0921",
        "layout": "4房(室)2廳1衛"
    },
    {
        "fake_id": 5,
        "url": "https://fake_url.com",
        "title": "信義區一般大樓",
        "price": 400000,
        "address": "台北市信義區松壽路",
        "type": "電梯大樓",
        "usage": None,
        "age": 10,
        "face": None,
        "env": "無",
        "size": 100,
        "short_stay": "12個月",
        "cook": True,
        "move_date": "2024年04月10日",
        "pet": "不可",
        "fee_contain": True,
        "gender": "男女皆可",
        "deposit": -1,
        "identy": "不限",
        "stay_landlord": True,
        "park": True,
        "equip": ["熱水器", "天然瓦斯", "洗衣機", "瓦斯爐", "冰箱", "冷氣"],
        "furniture": ["衣櫃"],
        "floor": "3 / 4 樓",
        "corner": True,
        "center": False,
        "top_add": False,
        "img_url": "https://pic.hfcdn.com/res/DrawImage/ShowPic/400/300/HFRENT05/1831862/1?t=0921",
        "layout": "4房(室)2廳1衛"
    },
    {
        "fake_id": 6,
        "title": "大安區四房高級住宅",
        "price": 500000,
        "address": "台北市大安區延吉街",
        "type": "電梯大樓",
        "usage": None,
        "age": 10,
        "face": None,
        "env": "無",
        "size": 100,
        "short_stay": "12個月",
        "cook": True,
        "move_date": "2024年04月10日",
        "pet": "不可",
        "fee_contain": True,
        "gender": "男女皆可",
        "deposit": -1,
        "identy": "不限",
        "stay_landlord": True,
        "park": True,
        "equip": ["熱水器", "天然瓦斯", "洗衣機", "瓦斯爐", "冰箱", "冷氣"],
        "furniture": ["衣櫃"],
        "floor": "3 / 4 樓",
        "corner": True,
        "center": False,
        "top_add": False,
        "img_url": "https://pic.hfcdn.com/res/DrawImage/ShowPic/400/300/HFRENT05/1831862/1?t=0921",
        "layout": "4房(室)2廳1衛"
    },
    {
        "fake_id": 7,
        "url": "https://fake_url.com",
        "title": "大安區四房高級住宅",
        "price": 200000,
        "address": "台北市大安區忠孝東路",
        "type": "電梯大樓",
        "usage": None,
        "age": 10,
        "face": None,
        "env": "無",
        "size": 100,
        "short_stay": "12個月",
        "cook": True,
        "move_date": "2024年04月10日",
        "pet": "不可",
        "fee_contain": True,
        "gender": "男女皆可",
        "deposit": -1,
        "identy": "不限",
        "stay_landlord": True,
        "park": True,
        "equip": ["熱水器", "天然瓦斯", "洗衣機", "瓦斯爐", "冰箱", "冷氣"],
        "furniture": ["衣櫃"],
        "floor": "3 / 4 樓",
        "corner": True,
        "center": False,
        "top_add": False,
        "img_url": "https://pic.hfcdn.com/res/DrawImage/ShowPic/400/300/HFRENT05/1831862/1?t=0921",
        "layout": "4房(室)2廳1衛"
    },
    {
        "fake_id": 8,
        "url": "https://fake_url.com",
        "title": "大安區四房高級住宅",
        "price": 200000,
        "address": "台北市信義區松延路",
        "type": "電梯大樓",
        "usage": None,
        "age": 10,
        "face": None,
        "env": "無",
        "size": 100,
        "short_stay": "12個月",
        "cook": True,
        "move_date": "2024年04月10日",
        "pet": "不可",
        "fee_contain": True,
        "gender": "男女皆可",
        "deposit": -1,
        "identy": "不限",
        "stay_landlord": True,
        "park": True,
        "equip": ["熱水器", "天然瓦斯", "洗衣機", "瓦斯爐", "冰箱", "冷氣"],
        "furniture": ["衣櫃"],
        "floor": "3 / 4 樓",
        "corner": True,
        "center": False,
        "top_add": False,
        "img_url": "https://pic.hfcdn.com/res/DrawImage/ShowPic/400/300/HFRENT05/1831862/1?t=0921",
        "layout": "4房(室)2廳1衛"
    },
    {
        "fake_id": 10,
        "title": "信義區四房高級住宅",
        "price": 200000,
        "address": "台北市信義區松壽路",
        "type": "電梯大樓",
        "usage": None,
        "age": 10,
        "face": None,
        "env": "無",
        "size": 100,
        "short_stay": "12個月",
        "cook": True,
        "move_date": "2024年04月10日",
        "pet": "不可",
        "fee_contain": True,
        "gender": "男女皆可",
        "deposit": -1,
        "identy": "不限",
        "stay_landlord": True,
        "park": True,
        "equip": ["熱水器", "天然瓦斯", "洗衣機", "瓦斯爐", "冰箱", "冷氣"],
        "furniture": ["衣櫃"],
        "floor": "3 / 4 樓",
        "corner": True,
        "center": False,
        "top_add": False,
        "img_url": "https://pic.hfcdn.com/res/DrawImage/ShowPic/400/300/HFRENT05/1831862/1?t=0921",
        "layout": "4房(室)2廳1衛"
    }
]


def insert_fake_house(house):
    house_id = get_next_house_id()
    house = {
        "id": house_id,
        "url": "https://fake_url" + f"/{house_id}." + "com",
        "title": house["title"],
        "price": house["price"],
        "address": house["address"],
        "type": house["type"],
        "usage": house["usage"],
        "age": house["age"],
        "face": house["face"],
        "env": house["env"],
        "size": house["size"],
        "short_stay": house["short_stay"],
        "cook": house["cook"],
        "move_date": house["move_date"],
        "pet": house["pet"],
        "fee_contain": house["fee_contain"],
        "gender": house["gender"],
        "deposit": house["deposit"],
        "identy": house["identy"],
        "stay_landlord": house["stay_landlord"],
        "park": house["park"],
        "equip": house["equip"],
        "furniture": house["furniture"],
        "floor": house["floor"],
        "corner": house["corner"],
        "center": house["center"],
        "top_add": house["top_add"],
        "img_url": house["img_url"],
        "layout": house["layout"],
        "updated_at": datetime.now()
    }
    house_collection.insert_one(house)
    print("Fake house inserted", "id", house_id)


for house in house_data:
    insert_fake_house(house)
    time.sleep(10)
