import json
from faker import Faker
import random
from dotenv import load_dotenv
import pymongo
import os

fake = Faker()


dotenv_path = '/Users/hojuicheng/Desktop/personal_project/Appworks_Personal/.env'
load_dotenv(dotenv_path)

# Mongo atlas
CONNECTION_STRING = os.getenv("MONGO_ATLAS_USER")
client = pymongo.MongoClient(CONNECTION_STRING)

introduction_list = [
    "Are you searching for a roommate who enjoys movie nights and game days? Let's connect!",
    "Looking for someone who values cleanliness and organization? Let's chat and see if we're a match!",
    "If you love cooking and sharing meals, we might just make the perfect roommates. Let's cook together and see!",
    "Dreaming of finding a roommate who respects personal space but is also up for occasional hangouts? Let's meet up and chat!",
    "Are you seeking a roommate who shares a passion for fitness and healthy living? Let's motivate each other to stay active!",
    "Looking for a friendly roommate who enjoys exploring the city on weekends? Let's hang out and explore together!",
    "Hoping to find a roommate who pays bills on time and respects quiet hours? Let's team up and make apartment life easy!",
    "Seeking a roommate who enjoys quiet nights in with a good book and a cup of tea? Let's relax and unwind together!",
    "If you're into music and up for jam sessions, we might just be the perfect roommates. Let's make some noise!",
    "Looking for a roommate who enjoys outdoor activities like hiking and biking? Let's hit the trails and explore nature together!",
    "If you're pet-friendly and open to sharing the apartment with a furry friend, let's welcome them in and make our space cozy!",
    "Seeking a roommate who is environmentally conscious and enjoys sustainable living practices? Let's go green and make a positive impact!",
    "Hoping to find a roommate who is a morning person and enjoys starting the day with a cup of coffee and a sunrise? Let's rise and shine together!",
    "Looking for someone who enjoys DIY projects and decorating the apartment? Let's get creative and personalize our space!",
    "Seeking a roommate who is a night owl and enjoys late-night conversations over pizza and movies? Let's bond and make memories!",
    "If you work from home and value a quiet and productive environment, let's create a home office space that works for both of us!",
    "Are you a student who appreciates study sessions and academic discussions? Let's ace our exams and conquer our goals together!",
    "Looking for a roommate who is a foodie and enjoys trying out new restaurants and cooking experiments? Let's indulge our taste buds!",
    "Seeking someone who enjoys arts and crafts and creative endeavors? Let's get crafty and add some DIY flair to our home!",
    "If you're a sports enthusiast who loves watching and playing sports, let's cheer for our favorite teams and hit the court together!",
    "Looking for a travel buddy who enjoys planning trips and exploring new destinations? Let's embark on adventures and make memories!",
    "Seeking a gaming buddy who enjoys gaming marathons and multiplayer challenges? Let's level up and conquer virtual worlds together!",
    "If you're a tech geek who loves discussing gadgets and innovations, let's geek out and explore the latest tech trends together!",
    "Looking for a fitness buddy who enjoys workout sessions and outdoor activities? Let's break a sweat and stay active together!",
    "Seeking a movie buddy who enjoys movie nights and film marathons? Let's binge-watch our favorite movies and discover new ones!",
    "If you're an animal lover who enjoys spending time with pets, let's cuddle with furry friends and share the love!",
    "Looking for someone who enjoys playing instruments and attending concerts? Let's jam and dance to the rhythm together!",
    "Seeking a fashionista who loves shopping and styling outfits? Let's swap clothes and share fashion tips!",
    "If you're a bookworm who enjoys reading and discussing literature, let's start a book club and explore new worlds together!",
    "Looking for a photography enthusiast who enjoys capturing moments and exploring the art of photography? Let's strike a pose and snap some pics!",
    "Seeking a plant lover who enjoys gardening and decorating the apartment with greenery? Let's grow a garden and add some life to our space!",
    "If you're a social butterfly who loves hosting gatherings and meeting new people, let's throw parties and make new friends together!",
    "Looking for a minimalist who enjoys decluttering and organizing the space? Let's embrace simplicity and create a zen environment!",
    "Seeking a yoga enthusiast who enjoys practicing mindfulness and meditation? Let's find inner peace and balance together!",
    "If you're into language learning and cultural exchange, let's explore new languages and broaden our horizons together!",
    "Looking for someone who enjoys upcycling and repurposing furniture? Let's transform our space and create something unique together!",
    "Seeking a coffee connoisseur who enjoys brewing specialty coffees and exploring different coffee shops? Let's caffeinate and savor the flavors together!",
    "If you're a night market enthusiast who enjoys exploring local markets and street food, let's feast on delicious treats and enjoy the night!",
    "Looking for a karaoke buddy who enjoys singing and performing? Let's hit the karaoke bars and sing our hearts out together!",
    "Seeking a beach lover who enjoys sunbathing and beach volleyball? Let's soak up the sun and enjoy the beach life together!",
    "If you're a dog person who enjoys walking and playing with dogs, let's take furry friends for walks and play fetch together!",
    "Looking for someone who enjoys analyzing films and discussing cinematic techniques? Let's review movies and critique our favorite directors together!",
    "Seeking a fitness coach who enjoys designing workout routines and motivating others? Let's get fit and healthy together!",
    "If you're a tech guru who enjoys troubleshooting gadgets and setting up smart home devices, let's upgrade our living space together!",
    "Looking for a wine enthusiast who enjoys organizing wine tastings and pairing events? Let's uncork bottles and explore the world of wine together!",
    "Seeking a photography blogger who enjoys capturing moments and sharing photography tips? Let's snap photos and create visual stories together!",
    "If you're a stand-up comedian who enjoys making people laugh and entertaining, let's share jokes and have a good time together!",
    "Looking for a dance instructor who enjoys teaching dance classes and choreographing routines? Let's learn new moves and dance together!",
    "Seeking a theater actor who enjoys rehearsing plays and performing on stage? Let's rehearse lines and bring characters to life together!",
    "If you're a DIY interior designer who enjoys decorating spaces and renovating furniture, let's revamp our living space and create a cozy home together!",
    "Looking for a language exchange partner who enjoys practicing languages and cultural exchange? Let's swap languages and learn from each other together!",
    "Seeking a coffee roaster who enjoys roasting coffee beans and experimenting with different brewing methods? Let's roast, grind, and brew our own coffee blends together!",
    "If you're a food critic who enjoys reviewing restaurants and food trends, let's dine out and critique culinary delights together!",
    "Looking for a dance choreographer who enjoys creating dance routines and staging performances? Let's rehearse and showcase our moves together!",
    "Seeking a theater director who enjoys casting actors and producing theater productions? Let's audition and stage plays together!",
    "If you're a DIY home decorator who enjoys crafting home decor items and styling interiors, let's DIY and decorate our space together!",
    "Looking for a language interpreter who enjoys translating languages and facilitating communication? Let's bridge language barriers and connect cultures together!",
    "Seeking a coffee enthusiast who enjoys exploring coffee shops and tasting different coffee blends? Let's savor and appreciate the art of coffee together!",
    "If you're a food vlogger who enjoys creating food content and sharing dining experiences, let's document food adventures and become influencers together!",
    "Looking for a dance performer who enjoys choreographing dance routines and performing on stage? Let's rehearse and dazzle the audience together!",
    "Seeking a theater critic who enjoys analyzing plays and writing theater reviews? Let's attend shows and critique performances together!",
    "If you're a DIY enthusiast who enjoys upcycling and repurposing items, let's transform trash into treasure and create unique pieces together!",
    "Looking for a language teacher who enjoys teaching languages and practicing conversation? Let's improve our language skills and become polyglots together!",
    "Seeking a coffee aficionado who enjoys brewing artisanal coffee and sharing coffee knowledge? Let's delve into the world of coffee and awaken our senses together!",
    "If you're a food explorer who enjoys trying exotic cuisines and street food delicacies, let's embark on gastronomic adventures and tantalize our taste buds together!",
    "Looking for a dance enthusiast who enjoys attending dance workshops and participating in dance competitions? Let's learn new dance styles and bust a move together!",
    "Seeking a theater enthusiast who enjoys attending theater performances and discussing dramatic literature? Let's appreciate the art of theater and engage in lively discussions together!",
    "If you're a DIY artist who enjoys creating handmade crafts and upcycling materials, let's unleash our creativity and decorate our space with handmade treasures together!",
    "Looking for a language lover who enjoys practicing languages and cultural exchange? Let's dive into language immersion and learn from each other together!",
    "Seeking a coffee addict who enjoys exploring coffee culture and trying new brews? Let's embark on a caffeine-fueled adventure and discover our favorite coffee spots together!",
    "If you're a foodie who enjoys experimenting with recipes and hosting dinner parties, let's cook up a storm and feast on delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance showcases? Let's refine our dance skills and perform on stage together!",
    "Seeking a theater buff who enjoys attending theater festivals and supporting local productions? Let's celebrate the art of theater and enjoy captivating performances together!",
    "If you're a DIY guru who enjoys tackling home improvement projects and crafting handmade items, let's roll up our sleeves and beautify our space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes, let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the world of theater and appreciate the magic of live performances together!",
    "If you're a DIY artist who enjoys creating handmade crafts and DIY projects? Let's unleash our creativity and transform ordinary materials into works of art together!",
    "Looking for a language enthusiast who enjoys learning new languages and practicing conversation? Let's immerse ourselves in language immersion and explore new cultures together!",
    "Seeking a coffee aficionado who enjoys discovering new coffee blends and brewing techniques? Let's explore the coffee scene and savor the finest brews together!",
    "If you're a foodie who enjoys trying out new dishes and exploring culinary trends? Let's embark on culinary adventures and savor gastronomic delights together!",
    "Looking for a dance fanatic who enjoys attending dance classes and participating in dance workshops? Let's groove to the rhythm and express ourselves through movement together!",
    "Seeking a theater buff who enjoys attending theater productions and analyzing dramatic performances? Let's engage in meaningful discussions and appreciate the art of theater together!",
    "If you're a DIY enthusiast who enjoys crafting handmade items and decorating the home? Let's unleash our creativity and add personal touches to our living space together!",
    "Looking for a language learner who enjoys practicing languages and exploring cultural diversity? Let's engage in language exchange and learn from each other's linguistic backgrounds together!",
    "Seeking a coffee lover who enjoys discovering new coffee blends and brewing techniques? Let's embark on a coffee-tasting journey and explore the world of specialty coffee together!",
    "If you're a food enthusiast who enjoys cooking and experimenting with recipes? Let's share culinary experiences and create delicious meals together!",
    "Looking for a dance aficionado who enjoys attending dance performances and participating in dance workshops? Let's express ourselves through dance and embrace the joy of movement together!",
    "Seeking a theater enthusiast who enjoys attending theater festivals and supporting local artists? Let's immerse ourselves in the"
]

additional_notes_list = fake_additional_note = [
    "I'm an early riser, so I usually go to bed early and wake up refreshed.",
    "I'm a night owl, so I tend to stay up late and sleep in.",
    "I'm a morning person, so I like to get up early to make breakfast and start my day.",
    "I'm a night person, so I prefer to sleep in and have a late breakfast.",
    "I enjoy cooking and experimenting with new recipes, so I often prepare homemade meals.",
    "I'm not much of a cook, so I rely on quick and easy meals or takeout.",
    "I have a pet, so I make sure to feed and care for them before going to bed.",
    "I don't have any pets, so my home is quiet and pet-free.",
    "I'm a smoker, so I smoke outside or in designated areas to minimize the smell indoors.",
    "I'm a non-smoker, so I prefer to keep my home smoke-free.",
    "I have a high tolerance for noise, so I don't mind a bit of background noise while I sleep.",
    "I'm a light sleeper, so I prefer a quiet environment for a good night's rest.",
    "I'm very hygienic and keep my living space clean and organized.",
    "I'm laid-back when it comes to cleanliness and don't mind a bit of mess.",
    "I'm highly sensitive to noise, so I prefer a quiet environment for sleeping and studying.",
    "I'm not bothered by noise and can sleep through most disturbances.",
    "I enjoy cooking and often prepare elaborate meals from scratch.",
    "I prefer to keep things simple and opt for easy-to-make meals or takeout.",
    "I have a dog/cat, so I'm used to taking care of their needs and cleaning up after them.",
    "I'm a pet-free household, so my living space is clean and free of pet hair.",
    "I smoke occasionally, but I always do so outside or in well-ventilated areas.",
    "I'm a non-smoker and prefer to keep my home smoke-free for a healthier environment.",
    "I'm a heavy sleeper and can easily tune out noise when I'm asleep.",
    "I'm a light sleeper and prefer a quiet environment for sleeping and relaxation.",
    "I'm meticulous about cleanliness and keep my living space neat and tidy at all times.",
    "I'm easygoing when it comes to cleanliness and don't mind a bit of clutter.",
    "I'm sensitive to noise and prefer to live in a quiet neighborhood away from busy streets.",
    "I'm not bothered by noise and can sleep soundly even with background sounds.",
    "I enjoy cooking and often try out new recipes to expand my culinary skills.",
    "I'm not much of a cook and prefer simple meals that require minimal preparation.",
    "I have a pet snake/fish, so I don't need to worry about pet-related chores like walking or grooming.",
    "I don't have any pets, so my living space is clean and free of animal hair or odors.",
    "I smoke occasionally, but I'm mindful of others and always smoke outdoors.",
    "I'm a non-smoker and prefer to keep my home smoke-free for a healthier living environment.",
    "I'm a heavy sleeper and can easily sleep through noise or disturbances.",
    "I'm a light sleeper and prefer a quiet environment for a restful night's sleep.",
    "I'm particular about cleanliness and prefer to keep my living space tidy and organized.",
    "I'm relaxed about cleanliness and don't mind a bit of mess or clutter.",
    "I'm sensitive to noise and prefer to live in a quiet neighborhood away from traffic or loud neighbors.",
    "I'm not easily disturbed by noise and can sleep soundly in most environments.",
    "I enjoy cooking and often host dinner parties or potlucks with friends.",
    "I prefer to eat out or order takeout rather than cooking at home.",
    "I have a pet bird/rabbit, so I'm used to cleaning cages and providing fresh food and water.",
    "I don't have any pets, so my home is clean and allergen-free.",
    "I'm a social smoker and only smoke when I'm out with friends or at special occasions.",
    "I'm a non-smoker and prefer to keep my living space free of smoke and odors.",
    "I'm a heavy sleeper and rarely wake up to noise or disturbances.",
    "I'm a light sleeper and prefer a quiet environment for sleeping and relaxation.",
    "I'm meticulous about cleanliness and keep my living space spotless at all times.",
    "I'm laid-back when it comes to cleanliness and don't mind a bit of mess or clutter.",
    "I'm sensitive to noise and prefer to live in a quiet neighborhood away from busy streets or construction sites.",
    "I'm not bothered by noise and can sleep soundly even with background sounds or music.",
    "I enjoy cooking and often try out new recipes from cookbooks or online sources.",
    "I'm not much of a cook and prefer quick and easy meals that require minimal effort.",
    "I have a pet hamster/guinea pig, so I'm used to cleaning cages and providing fresh bedding and food.",
    "I don't have any pets, so my living space is clean and free of pet-related messes.",
    "I'm a social smoker and only smoke when I'm out with friends or in social settings.",
    "I'm a non-smoker and prefer to keep my home smoke-free for a healthier living environment.",
    "I'm a heavy sleeper and can easily sleep through noise or disturbances without waking up.",
    "I'm a light sleeper and prefer a quiet environment for sleeping and relaxation.",
    "I'm meticulous about cleanliness and keep my living space tidy and organized at all times.",
    "I'm easygoing when it comes to cleanliness and don't mind a bit of clutter or mess.",
    "I'm sensitive to noise and prefer to live in a quiet neighborhood away from busy streets or loud neighbors.",
    "I'm not easily disturbed by noise and can sleep soundly in most environments.",
    "I enjoy cooking and often experiment with new ingredients and flavors to create delicious meals.",
    "I'm not much of a cook and prefer simple meals that require minimal preparation and cleanup.",
    "I have a pet turtle/tortoise, so I'm used to maintaining an aquarium or terrarium and providing fresh food and water.",
    "I don't have any pets, so my living space is clean and free of animal-related messes.",
    "I'm a social smoker and only smoke when I'm out with friends or at social gatherings.",
    "I'm a non-smoker and prefer to keep my home smoke-free for a healthier living environment.",
    "I'm a heavy sleeper and rarely wake up to noise or disturbances during the night.",
    "I'm a light sleeper and prefer a quiet environment for sleeping and relaxation.",
    "I'm meticulous about cleanliness and keep my living space neat and organized at all times.",
    "I'm relaxed about cleanliness and don't mind a bit of mess or clutter in my living space.",
    "I'm sensitive to noise and prefer to live in a quiet neighborhood away from traffic or construction noise.",
    "I'm not easily disturbed by noise and can sleep soundly even with background sounds or music playing.",
    "I enjoy cooking and often invite friends over for dinner parties or potlucks.",
    "I prefer to eat out or order takeout rather than cooking at home.",
    "I have a pet lizard/snake, so I'm used to maintaining a terrarium and providing fresh food and water.",
    "I don't have any pets, so my living space is clean and free of pet-related messes or odors.",
    "I'm a social smoker and only smoke when I'm out with friends or at social events.",
    "I'm a non-smoker and prefer to keep my home smoke-free for a healthier living environment.",
    "I'm a heavy sleeper and can easily sleep through noise or disturbances without waking up.",
    "I'm a light sleeper and prefer a quiet environment for sleeping and relaxation.",
    "I'm meticulous about cleanliness and keep my living space tidy and organized at all times.",
    "I'm easygoing when it comes to cleanliness and don't mind a bit of clutter or mess in my living space.",
    "I'm sensitive to noise and prefer to live in a quiet neighborhood away from busy streets or loud neighbors.",
    "I'm not easily disturbed by noise and can sleep soundly in most environments.",
    "I enjoy cooking and often experiment with new recipes and ingredients to create delicious meals.",
    "I'm not much of a cook and prefer simple meals that require minimal preparation and cleanup.",
    "I have a pet bird/hamster, so I'm used to cleaning cages and providing fresh bedding and food.",
    "I don't have any pets, so my living space is clean and free of pet-related messes or odors.",
    "I'm a social smoker and only smoke when I'm out with friends or at social gatherings.",
    "I'm a non-smoker and prefer to keep my home smoke-free for a healthier living environment.",
    "I'm a heavy sleeper and rarely wake up to noise or disturbances during the night.",
    "I'm a light sleeper and prefer a quiet environment for sleeping and relaxation.",
    "I'm meticulous about cleanliness and keep my living space neat and organized at all times.",
    "I'm relaxed about cleanliness and don't mind a bit of mess or clutter in my living space.",
    "I'm sensitive to noise and prefer to live in a quiet neighborhood away from traffic or construction noise.",
    "I'm not easily disturbed by noise and can sleep soundly even with background sounds or music playing."
]

num_users = 1000

# Sample data
user_info = {
    "_id": {"$oid": "661f6e0a237431f759d71840"},
    "user_id": {"$numberInt": "8"},
    "username": "Ray",
    "email": "ray67672@gmail.com",
    "password": "pbkdf2:sha256:260000$ZHk3mkyDR2BFBK9K$e1c99a487490e48599f72add5c86434364b963a2d9fa40ebc0da19553b0f7b5d",
    "basic_info": {
        "gender": "male",
        "identity": "student",
        "partner": "yes",
        "introduction": "I am ok"
    },
    "house_preference": {
        "price": "163793",
        "house_age": "25",
        "zone": ["中正區", "文山區"],
        "stay_with_landlord": "yes",
        "park_nearby": "yes"
    },
    "routine": {
        "sleepTime": "14:12",
        "wakeUpTime": "00:32",
        "hygieneTolerance": {"$numberInt": "5"},
        "noiseTolerance": {"$numberInt": "3"},
        "cookOptions": "sometimes",
        "petOptions": "yes",
        "smokeOptions": "yes",
        "additionalNotes": "no"
    },
    "furniture_preference": {
        "equipment": ["internet", "gasStove"],
        "furniture": ["diningTable", "chair"]
    }
}

# Function to generate fake user data
# 台北市所有行政區
taipei_districts = ["內湖區", "中山區", "松山區", "士林區", "南港區",
                    "萬華區", "大同區", "北投區", "中正區", "文山區", "大安區", "信義區"]
taipei_weights = [4] * len(taipei_districts)
# 新北市所有行政區
new_taipei_districts = ["萬里區", "金山區", "板橋區", "汐止區", "深坑區", "石碇區", "瑞芳區", "平溪區", "雙溪區", "貢寮區", "新店區", "坪林區", "烏來區",
                        "永和區", "中和區", "土城區", "三峽區", "樹林區", "鶯歌區", "三重區", "新莊區", "泰山區", "林口區", "蘆洲區", "五股區", "八里區", "淡水區", "三芝區", "石門區"]
new_taipei_weights = [1] * len(new_taipei_districts)
districts = taipei_districts + new_taipei_districts
weights = taipei_weights + new_taipei_weights


def get_next_user_id():
    # Find and update the user_id counter
    counter_doc = client['personal_project']['user'].counters.find_one_and_update(
        {"_id": "user_id"},
        {"$inc": {"seq": 1}},
        upsert=True,  # Create the counter if it doesn't exist
        return_document=True
    )
    return counter_doc["seq"]


def generate_sleep_time():
    hours = random.choice([random.randint(20, 23),  random.randint(
        0, 3)])  # Generate random hour between 21 and 23
    # Every 30 minutes
    minutes = random.choice([0, 30])
    return f"{hours:02d}:{minutes:02d}"


def generate_wake_up_time():
    hours = random.randint(4, 12)  # Generate random hour between 5 and 8
    minutes = random.choice([0, 30])  # Every 30 minutes
    return f"{hours:02d}:{minutes:02d}"


def generate_fake_user():
    district_choice_num = random.randint(1, 12)
    equipment_choice_num = random.randint(1, 15)
    furniture_choice_num = random.randint(1, 9)
    user_id = get_next_user_id()

    random_step = random.randint(1, 200)
    random_price = random_step * 1000

    user = {
        "user_id": user_id,
        "username": fake.first_name(),
        "email": fake.email(),
        "password": fake.password(),
        "basic_info": {
            "gender": random.choice(["male", "female", "non-binary"]),
            "identity": fake.random_element(["student", "worker", "retiree", "doctor", "engineer", "teacher", "engineer", "designer", "artist", "other"]),
            "partner": fake.random_element(["yes", "no"]),
            "introduction": fake.random_element(introduction_list)
        },
        "house_preference": {
            "price": random_price,
            "house_age": fake.random_int(min=1, max=100),
            "zone": random.choices(districts, weights=weights, k=district_choice_num),
            "stay_with_landlord": fake.random_element(["yes", "no"]),
            "park_nearby": fake.random_element(["yes", "no"])
        },
        "routine": {
            "sleepTime": generate_sleep_time(),
            "wakeUpTime": generate_wake_up_time(),
            "hygieneTolerance": fake.random_int(min=1, max=10),
            "noiseTolerance": fake.random_int(min=1, max=10),
            "cookOptions": fake.random_element(["seldoms", "sometimes", "always"]),
            "petOptions": fake.random_element(["yes", "no"]),
            "smokeOptions": fake.random_element(["yes", "no"]),
            "additionalNotes": fake.random_element(additional_notes_list)
        },
        "items_preference": {
            "equipment": random.sample(["internet", "cableTV", "washingMachine", "dryer", "dryingMachine", "waterDispenser", "waterFilter", "lcdTV", "refrigerator", "gasStove", "microwave", "oven", "naturalGas", "inductionCooker", "electricFan"], equipment_choice_num),
            "furniture": random.sample(["wardrobe", "diningTable", "diningChair", "cabinet", "singleBed", "doubleBed", "desk", "chair", "sofa"], furniture_choice_num)
        }
    }
    return user


# Generate 10 fake users
fake_users = [generate_fake_user() for _ in range(num_users)]


# Print generated users
# Put fake users into json file
with open("/Users/hojuicheng/Desktop/personal_project/Appworks_Personal/data/fake_users.json", "w") as f:
    json.dump(fake_users, f, ensure_ascii=False)


# Insert fake users into MongoDB
db = client["personal_project"]
user_collection = db["user"]

for user in fake_users:
    print(user["username"])

print(len(fake_users))


# Delete users with user_id >= 119
deelte = input("Do you want to delete users with user_id >= 119? (y/n)")
if deelte == "y":
    threshold_user_id = 119
    user_collection.delete_many({'user_id': {'$gte': threshold_user_id}})

insert = input("Do you want to insert fake users into MongoDB? (y/n)")
if insert == "y":

    for user in fake_users:
        user_collection.insert_one(user)
    print("Fake users inserted into MongoDB.")
